name: CI

on:
  workflow_dispatch:

jobs:
  container:
    runs-on: ubuntu-latest
    container: lpodkalicki/avr-toolchain
    steps:
      - uses: actions/checkout@master
      - run: cmake
        name: CMake
      - run: make
        name: Make
